routes/web.php
            Route::get('admin/create', 'dashboard\AdministrationController@admin_create')->name('admin_create')->middleware('perms:administration');
            Route::post('admin/store', 'dashboard\AdministrationController@admin_store')->name('admin_store')->middleware('perms:administration');
            Route::get('admin/edit/{id?}', 'dashboard\AdministrationController@admin_edit')->name('admin_edit')->middleware('perms:administration');
            Route::post('admin/update', 'dashboard\AdministrationController@admin_update')->name('admin_update')->middleware('perms:administration');
            Route::get('admin/delete/{id?}', 'dashboard\AdministrationController@admin_delete')->name('admin_delete')->middleware('perms:administration');
        });

        Route::group(['prefix' => 'nationality'], function () {
            Route::get('/', 'dashboard\NationalitiesController@index')->name('nationality')->middleware('perms:nationality');
            Route::get('create', 'dashboard\NationalitiesController@create')->name('nationality_create')->middleware('perms:nationality');
            Route::post('store', 'dashboard\NationalitiesController@store')->name('nationality_store')->middleware('perms:nationality');
            Route::get('edit/{id?}', 'dashboard\NationalitiesController@edit')->name('nationality_edit')->middleware('perms:nationality');
            Route::post('update', 'dashboard\NationalitiesController@update')->name('nationality_update')->middleware('perms:nationality');
            Route::get('delete/{id?}', 'dashboard\NationalitiesController@delete')->name('nationality_delete')->middleware('perms:nationality');
        });

        Route::group(['prefix' => 'user'], function () {
            Route::get('/', 'dashboard\UserController@index')->name('users')->middleware('perms:users');
            Route::get('create', 'dashboard\UserController@create')->name('create_user')->middleware('perms:create_user');
            Route::post('store', 'dashboard\UserController@store')->name('user_store')->middleware('perms:create_user');
            Route::get('edit/{id?}', 'dashboard\UserController@edit')->name('user_edit')->middleware('perms:user_edit');
            Route::PUT('update', 'dashboard\UserController@update')->name('user_update')->middleware('perms:user_edit');
            Route::get('delete/{id?}', 'dashboard\UserController@delete')->name('user_delete')->middleware('perms:user_delete');
            Route::get('trashed', 'dashboard\UserController@trashed')->name('user_trashed')->middleware('perms:user_trashed');
            Route::get('restore/{id?}', 'dashboard\UserController@restore')->name('user_restore')->middleware('perms:user_trashed');
            Route::get('force_delete/{id?}', 'dashboard\UserController@force_delete')->name('user_force_delete')->middleware('perms:user_trashed');
            Route::get('profile/{id?}', 'dashboard\UserController@profile')->name('user_profile')->middleware('perms:user_profile');
            Route::post('wallet', 'dashboard\UserController@wallet')->name('user_wallet')->middleware('perms:user_wallet');
            Route::get('live_search_4_driver/{id?}', 'dashboard\UserController@live_search_4_driver')->name('live_search_4_driver')->middleware('perms:user_profile');

        });
            //----------------------- restuatants ------------------------
        Route::group(['prefix' => 'restaurant'], function () {
                Route::get('/', 'dashboard\RestaurantController@index')->name('restaurants')->middleware('perms:restaurants');
                Route::get('create', 'dashboard\RestaurantController@create')->name('create_restaurant')->middleware('perms:create_restaurant');
                Route::post('store', 'dashboard\RestaurantController@store')->name('restaurant_store')->middleware('perms:create_restaurant');
                Route::get('edit/{id?}', 'dashboard\RestaurantController@edit')->name('restaurant_edit')->middleware('perms:restaurant_edit');
                Route::PUT('update', 'dashboard\RestaurantController@update')->name('restaurant_update')->middleware('perms:restaurant_edit');
                Route::get('delete/{id?}', 'dashboard\RestaurantController@delete')->name('restaurant_delete')->middleware('perms:restaurant_delete');
                Route::get('profile/{id?}', 'dashboard\RestaurantController@profile')->name('restaurant_admin_profile')->middleware('perms:restaurant_admin_profile');
            });


        Route::group(['prefix' => 'ad'], function () {
            Route::get('/', 'dashboard\AdController@index')->name('ads')->middleware('perms:ads');
            Route::get('delete/{id?}', 'dashboard\AdController@delete')->name('ad_delete')->middleware('perms:ad_delete');
            Route::get('ad/{id?}', 'dashboard\AdController@ad')->name('ad_details')->middleware('perms:ad_details');
        });

        Route::group(['prefix' => 'bank_account'], function () {
            Route::get('/', 'dashboard\BankAccountController@index')->name('bank_account')->middleware('perms:bank_account');
            Route::get('create', 'dashboard\BankAccountController@create')->name('bank_account_create')->middleware('perms:bank_account_create');
            Route::post('store', 'dashboard\BankAccountController@store')->name('bank_account_store')->middleware('perms:bank_account_create');
            Route::get('edit/{id?}', 'dashboard\BankAccountController@edit')->name('bank_account_edit')->middleware('perms:bank_account_edit');
            Route::post('update', 'dashboard\BankAccountController@update')->name('bank_account_update')->middleware('perms:bank_account_edit');
            Route::get('delete/{id?}', 'dashboard\BankAccountController@delete')->name('bank_account_delete')->middleware('perms:bank_account_delete');
        });

        Route::group(['prefix' => 'contacts'], function () {
            Route::get('/', 'dashboard\UserMessageController@contacts')->name('contacts')->middleware('perms:contacts');
            Route::get('delete/{id?}', 'dashboard\UserMessageController@delete_contact')->name('delete_contact')->middleware('perms:contact_delete');
        });

        Route::group(['prefix' => 'reports'], function () {
            Route::get('/', 'dashboard\SettingController@reports')->name('reports')->middleware('perms:reports');
            Route::get('delete/{id?}', 'dashboard\SettingController@delete_report')->name('delete_report')->middleware('perms:report_delete');
        });



        Route::group(['prefix' => 'category'], function () {
            Route::get('/', 'dashboard\CategoryController@index')->name('categories')->middleware('perms:categories');
            Route::get('create', 'dashboard\CategoryController@create')->name('category_create')->middleware('perms:category_create');
            Route::post('store', 'dashboard\CategoryController@store')->name('category_store')->middleware('perms:category_create');
            Route::get('edit/{id?}', 'dashboard\CategoryController@edit')->name('category_edit')->middleware('perms:category_edit');
            Route::post('update', 'dashboard\CategoryController@update')->name('category_update')->middleware('perms:category_edit');
            Route::get('delete/{id?}', 'dashboard\CategoryController@delete')->name('category_delete')->middleware('perms:category_delete');
        });

        Route::group(['prefix' => 'service'], function () {
            Route::get('/', 'dashboard\ServiceController@index')->name('services')->middleware('perms:services');
            Route::get('create', 'dashboard\ServiceController@create')->name('service_create')->middleware('perms:service_create');
            Route::post('store', 'dashboard\ServiceController@store')->name('service_store')->middleware('perms:service_create');
            Route::get('edit/{id?}', 'dashboard\ServiceController@edit')->name('service_edit')->middleware('perms:service_edit');
            Route::post('update', 'dashboard\ServiceController@update')->name('service_update')->middleware('perms:service_edit');
            Route::get('delete/{id?}', 'dashboard\ServiceController@delete')->name('service_delete')->middleware('perms:service_delete');
        });

        Route::group(['prefix' => 'option'], function () {
            Route::get('/', 'dashboard\OptionController@index')->name('options')->middleware('perms:options');
            Route::get('create', 'dashboard\OptionController@create')->name('option_create')->middleware('perms:option_create');
            Route::post('store', 'dashboard\OptionController@store')->name('option_store')->middleware('perms:option_create');
            Route::get('edit/{id?}', 'dashboard\OptionController@edit')->name('option_edit')->middleware('perms:option_edit');
            Route::post('update', 'dashboard\OptionController@update')->name('option_update')->middleware('perms:option_edit');
            Route::get('delete/{id?}', 'dashboard\OptionController@delete')->name('option_delete')->middleware('perms:option_delete');
        });

        // Route::group(['prefix' => 'type'], function () {
        //     Route::get('/', 'dashboard\TypeController@index')->name('types')->middleware('perms:types');
        //     Route::get('create', 'dashboard\TypeController@create')->name('type_create')->middleware('perms:type_create');
        //     Route::post('store', 'dashboard\TypeController@store')->name('type_store')->middleware('perms:type_create');
        //     Route::get('edit/{id?}', 'dashboard\TypeController@edit')->name('type_edit')->middleware('perms:type_edit');
        //     Route::post('update', 'dashboard\TypeController@update')->name('type_update')->middleware('perms:type_edit');
        //     Route::get('delete/{id?}', 'dashboard\TypeController@delete')->name('type_delete')->middleware('perms:type_delete');
        // });

        Route::group(['prefix' => 'type'], function () {

app/Dish.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dish extends Model
{
    protected $table = 'dishes';

    protected $fillable = ['user_id' , 'name' , 'image' , 'description' , 'price' , 'category_id'];

    public function getImageurlAttribute()
    {
        $image = Dish::where('id', $this->id)->first()->image;
        if (!$image) {
            return url('storage/app/dishes/default.png');
        }
        return url('storage/app/dishes/org') . '/' . $this->attributes['image'];
    }
    public function getImageurlorgAttribute()
    {
        $image = Dish::where('id', $this->id)->first()->image;
        if (!$image) {
            return url('storage/app/dishes/default.png');
        }
        return url('storage/app/dishes/org') . '/' . $this->attributes['image'];
    }


    public function user(){
        return $this->belongsTo(User::class);
    }
    public function category(){
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/api/DishController.php
<?php

namespace App\Http\Controllers\api;

use App\Dish;
use App\Http\Controllers\IMAGE_CONTROLLER;
use App\Http\Controllers\PARENT_API;
use App\Http\Requests\DishRequest;
use App\Http\Requests\DishDelete;
use App\Http\Requests\DishUpdate;
use App\Http\Resources\DishResource;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use JWTAuth;

class DishController extends PARENT_API
{
    public function store(DishRequest $request){
        $user_data = JWTAuth::parseToken()->toUser();
        $user = User::where('id' , $user_data->id)->first();
        $dish = Dish::create([
            'user_id' =>$user->id,
            'category_id' =>$request->category_id,
            'name' =>$request->name,
            'description' =>$request->description,
            'price' =>$request->price,
            'image' =>IMAGE_CONTROLLER::upload_single($request->image, 'storage/app/dishes'),
        ]);
        $this->data['data'] =  $dish;
        $this->data['status'] = "ok";
        $this->data['message'] = trans('app.messages.DishAdded');
        return response()->json($this->data, 200);
    }

    public function DishUpdate(DishUpdate $request){
        $dish = Dish::find($request->dish_id);
        if (!$dish){
            $this->data['data']=null;
            $this->data['status'] = "fails";
            $this->data['message'] = trans('dash.not_found');
            return response()->json($this->data, 405);
        }
        if ($request->name){
            $dish->name = $request->name;
        }
        if ($request->description){
            $dish->description = $request->description;
        }
        if ($request->price){
            $dish->price = $request->price;
        }
        if ($request->category_id){
            $dish->category_id = $request->category_id;
        }
        if ($request->image){
            $dish->image = IMAGE_CONTROLLER::upload_single($request->image, 'storage/app/dishes');
        }
        $dish->update();

        $this->data['data'] = $dish;
        $this->data['status'] = "ok";
        $this->data['message'] = trans('app.messages.DishUpdated');
        return response()->json($this->data, 200);
    }

    public function DishDelete(DishDelete $request){
        $dish = Dish::where('id' , $request['dish_id'])->first()->delete();

        $this->data['data'] =  "";
        $this->data['status'] = "ok";
        $this->data['message'] =trans( 'app.messages.DishDeleted');
        return response()->json($this->data, 200);
    }

    public function Dish(DishDelete $request){
        $dish = Dish::find($request->dish_id);
        if (!$dish){
            $this->data['data']=null;
            $this->data['status'] = "fails";
            $this->data['message'] = trans('dash.not_found');
            return response()->json($this->data, 405);
        }
        
        $this->data['data'] = new DishResource($dish);
        $this->data['status'] = "ok";
        $this->data['message'] = "";
        return response()->json($this->data, 200);
    }
}

app/Http/Controllers/dashboard/DishController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Dish;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DishController extends Controller
{
     public function __construct()
    {
        $this->data['squence_pages'][trans('الاطباق')] = route('dishes');
        $this->mainRedirect = 'dashboard.dishes.';
    }

    public function index()
    {
        $this->data['dishes'] = Dish::all();
        return view($this->mainRedirect . 'index', $this->data);
    }

    public function show($id)
    {
        $data['dish'] = Dish::find($id);
        return view($this->mainRedirect . 'view', $data);
    }

    public function delete($id = 0)
    {
        if (!$dish = Dish::find($id)) {
            return back()->with('class', 'alert alert-danger')->with('message', trans('dash.try_2_access_not_found_content'));
        }
        $dish->delete();
        return back()->with('class', 'alert alert-success')->with('message', trans('dash.deleted_successfully'));
    }
}

app/Http/Controllers/restaurant/AdController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Ad;
use App\Http\Controllers\PARENT_DASHBOARD;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdController extends PARENT_DASHBOARD
{
    public function index(){
        $data['ads'] = Ad::paginate(10);
        return view('dashboard.ad.index', $data);
    }
    public function ad($id){
        $data['ad'] = Ad::find($id);
        return view('dashboard.ad.ad', $data);
    }
    public function delete(Request $request ,  $id){
        $data['ad'] = Ad::find($id)->delete();
        $data['ads'] = Ad::paginate(10);

        if ($request->has('forward')) {
            $forward_url = url('dashboard/user');
            return redirect($forward_url);
        }else{
            return redirect()->route('ads' , $data);
        }


    }

}

app/Http/Controllers/restaurant/AdddController.php
<?php

namespace App\Http\Controllers\dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdddController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/restaurant/dishes/edit.blade.php
@extends('restaurant.layout')

@section('script')
    <!-- Theme JS files -->
    <script type="text/javascript" src="{{ url('public/dashboard_assets/material') }}/assets/js/plugins/forms/selects/select2.min.js"></script>
    <script type="text/javascript" src="{{ url('public/dashboard_assets/material') }}/assets/js/plugins/forms/styling/uniform.min.js"></script>
    <script type="text/javascript" src="{{ url('public/dashboard_assets/material') }}/assets/js/core/app.js"></script>
    <script type="text/javascript" src="{{ url('public/dashboard_assets/material') }}/assets/js/pages/form_layouts.js"></script>
    <script type="text/javascript" src="{{ url('public/dashboard_assets/material') }}/assets/js/pages/form_select2.js"></script>
    <script type="text/javascript" src="{{ url('public/dashboard_assets/material') }}/assets/js/plugins/ui/ripple.min.js"></script>

    <!-- /theme JS files -->

@endsection

@section('content')

<div class="row">
    <div class="col-md-6">

        <!-- Basic layout-->
        <form action="{{ route('restaurant_dishes_update') }}" class="form-horizontal" method="post" enctype="multipart/form-data">
            {{ Form::token() }}
            <input type="hidden" name="dish_id" value="{{ $dish->id }}" />
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title"> تعديل بيانات طبق </h5>
                    <div class="heading-elements">
                        <ul class="icons-list">
                            <li><a data-action="collapse"></a></li>
                            <li><a data-action="reload"></a></li>
                            <li><a data-action="close"></a></li>
                        </ul>
                    </div>
                </div>

                <div class="panel-body">


                    <div class="form-group">
                        <label class="col-lg-3 control-label">اسم الطبق</label>
                        <div class="col-lg-9">
                            <input type="text" class="form-control" name="name" placeholder="اسم الطبق" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-3 control-label">السعر</label>
                        <div class="col-lg-9">
                            <input type="text" class="form-control" name="price" placeholder="السعر" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-3 control-label">الوصف</label>
                        <div class="col-lg-9">
                            <input type="text" class="form-control" name="description" placeholder="الوصف" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-3 control-label display-block"> اخترالتصنيف </label>
                        <div class="col-lg-9">
                            <select name="category_id" class="select-border-color border-warning" >
                                <optgroup label="اختر التصنيف">
                                    @foreach ($categories as $category)
                                        @if($index->$category)
                                        @endif
                                        <option value="{{ $category->id }}" @if($category->country_id == $category->id) selected @endif> {{ $category->name_ar.' - '.$category->name_en }} </option>
                                    @endforeach
                                </optgroup>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-3 control-label"> {{ trans('dash.image') }}</label>
                        <div class="col-lg-6">
                            <input type="file" class="file-styled" name="image" >
                        </div>
                        <div class="col-lg-3">
                            <a href="{{ $dish->imageurlorg }}" data-popup="lightbox">
                                <img src="{{ $dish->imageurl }}" height="80" width="90" />
                            </a>
                        </div>
                    </div>



                    <div class="text-right">
                        <input type="submit" class="btn btn-primary" name="forward" value=" {{ trans('dash.update_and_forword_2_list') }} " />
                        <input type="submit" class="btn btn-success" name="back" value=" {{ trans('dash.update_and_come_back') }} " />
                    </div>
                </div>
            </div>
        </form>
        <!-- /basic layout -->

    </div>

</div>

</div>

@endsection

resources/views/restaurant/dishes/index.blade.php
@extends('restaurant.layout')

@section('script')
    <script type="text/javascript" src="{{ url('public/dashboard_assets') }}/js/plugins/media/fancybox.min.js"></script>
    <script type="text/javascript" src="{{ url('public/dashboard_assets') }}/js/pages/user_pages_team.js"></script>

    <script type="text/javascript" src="{{ url('public/dashboard_assets') }}/js/plugins/tables/datatables/datatables.min.js"></script>
	<script type="text/javascript" src="{{ url('public/dashboard_assets') }}/js/plugins/forms/selects/select2.min.js"></script>
	<script type="text/javascript" src="{{ url('public/dashboard_assets') }}/js/core/app.js"></script>
	<script type="text/javascript" src="{{ url('public/dashboard_assets') }}/js/pages/datatables_advanced.js"></script>
	<script type="text/javascript" src="{{ url('public/dashboard_assets') }}/js/plugins/ui/ripple.min.js"></script>
@endsection

@section('content')


<div class="panel panel-flat tb_padd">
    <div class="panel-heading">
        <h5 class="panel-title"> {{ trans('الاطباق والوجبات') }} </h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>
                <li><a data-action="close"></a></li>
            </ul>
        </div>
    </div>
    
    <table class="table table-condensed table-hover datatable-highlight">
        <thead>
            <tr>
                <th class="text-center"> # </th>
                <th class="text-center"> اسم المطعم </th>
                <th class="text-center"> {{ trans('اسم الطبق') }} </th>
                <th class="text-center"> السعر </th>
                <th class="text-center"> التصنيف </th>
                <th class="text-center"> {{ trans('dash.image') }} </th>
                <th class="text-center"> {{ trans('dash.actions') }} </th>
            </tr>
        </thead>
        <tbody>
            @forelse($dishes as $dish)
            <tr id="row_{{ $dish->id }}">
                <td> {{ $dish->id }} </td>
                <td> {{ $dish->user->full_name }} </td>
                <td> {{ $dish->name }} </td>
                <td> {{ $dish->price }} </td>
                <td> {{ $dish->category->name_ar }} </td>
                <td>
                    <a href="{{ $dish->imageurlorg }}" data-popup="lightbox">
                        <img src="{{ $dish->imageurl }}" height="100" width="100" />
                    </a>
                </td>
                <td class="text-center">
                    <a href="{{ route('restaurant_dishes_view',['id' => $dish->id ]) }}" class="btn btn-primary"> <i class="icon-touch"></i> </a>
                    <a href="{{ route('restaurant_dishes_edit',['id' => $dish->id ]) }}" class="btn btn-primary"> <i class="icon-pencil"></i> </a>
                    <a onclick="sweet_delete( ' {{ route('restaurant_dishes_delete').'/'.$dish->id }} ' , '{{ trans('dash.deleted_msg_confirm') }}' ,{{ $dish->id }} )" class="btn btn-danger" > <i class="icon-database-remove"></i> </a>
                </td>
            </tr>

            @empty
            @endforelse

        </tbody>
    </table>
</div>

@endsection

resources/views/restaurant/dishes/view.blade.php
@extends('restaurant.layout')

@section('script')
    <script type="text/javascript" src="{{ url('public/dashboard_assets/material') }}/assets/js/plugins/tables/datatables/datatables.min.js"></script>
	<script type="text/javascript" src="{{ url('public/dashboard_assets/material') }}/assets/js/plugins/media/fancybox.min.js"></script>
    <script type="text/javascript" src="{{ url('public/dashboard_assets/material') }}/assets/js/core/app.js"></script>
    <script type="text/javascript" src="{{ url('public/dashboard_assets/material') }}/assets/js/pages/user_pages_team.js"></script>
	<script type="text/javascript" src="{{ url('public/dashboard_assets/material') }}/assets/js/plugins/ui/ripple.min.js"></script>
@endsection

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-flat">
            <div class="panel-heading">
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="reload"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            <div class="panel-body">
                <ul class="nav nav-tabs nav-tabs-highlight">
                    <li class="active"><a href="#details-tab" data-toggle="tab"><i class="icon-menu7 position-left"></i> تفاصيل الطبق </a></li>
                </ul>
                <div class="tabbable nav-tabs-vertical nav-tabs-left">

                    <div class="tab-content">

                        <div class="tab-pane active has-padding" id="details-tab">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="panel panel-flat">
                                        <div class="panel-heading">
                                            <h5 class="panel-title"> تفاصيل الطبق </h5>
                                            <div class="heading-elements">
                                                <ul class="icons-list">
                                                    <li><a data-action="collapse"></a></li>
                                                </ul>
                                            </div>
                                        </div>

                                            <table class="table table-hover table-bordered table-hover">
                                                <tr class="success">
                                                    <td> اسم الطبق </td>
                                                    <td> {{ $dish->name }} </td>
                                                </tr>
                                                <tr class="success">
                                                    <td> اسم المطعم </td>
                                                    <td> {{ $dish->user->full_name }} </td>
                                                </tr>
                                                <tr class="success">
                                                    <td> وصف الطبق </td>
                                                    <td> {{$dish->description}} </td>
                                                </tr>

                                                <tr class="success">
                                                    <td> سعر الطبق </td>
                                                    <td> {{$dish->price}} </td>
                                                </tr>
                                                <tr class="danger">
                                                    <td> {{ trans('dash.image') }} </td>
                                                    <td>
                                                        <a href="{{ $dish->imageurlorg }}" data-popup="lightbox">
                                                            <img src="{{ $dish->imageurl }}" height="100" width="100" />
                                                        </a>
                                                    </td>
                                                </tr>

                                            </table>
                                            <br>
                                            @if($dish->status == "wait")
                                            <center>
                                                <a onclick="sweet_confirm_pay()" id="confirm_pay_btn" href="#" class="btn btn-success"> {{ trans('dash.do_dish_confirm') }} </a>
                                            </center>
                                            <br> <br>
                                            <center>
                                                <a onclick="sweet_confirm_refuse()" id="confirm_refuse_btn" href="#" class="btn btn-danger"> {{ trans('dash.do_dish_refuse') }} </a>
                                            </center>
                                            <br>
                                            @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection